### ISSUE TITLE
Add a build.cmd script

### ISSUE THREAD

**Issue by DavidBetteridge** [YorkCodeDojo/PacMan#10]
The build.cmd script should download and install the required version of .net core

Then run dotnet build

**Comment by kevbite** [comment]
within the `global.json` you can now include a `rollForward` field which allows you to use later version than specified:

```json
{
  "sdk": {
    "version": "3.1.000",
    "rollForward": "latestFeature"
  }
}
```

https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x#rollforward

**Comment by DavidBetteridge** [comment]
That works for me :-)
