### ISSUE TITLE
Ghosts are transitioning while in eyes

### ISSUE THREAD

**Issue by pgillett** [YorkCodeDojo/PacMan#100]
When a ghost is travelling back to the ghost house as eyes, the transition out of frightened is resetting it to Alive

**Comment by kevbite** [comment]
![pacman-2](https://user-images.githubusercontent.com/5544715/85210395-53e04000-b337-11ea-847d-cfd2457a687a.gif)

**Comment by pgillett** [comment]
That also brings another interesting issue. Watching the video, as he gets almost to the ghost house he turns left rather than right because he's targeting the top left corner of the house (which the left turn will be closer to)
