### ISSUE TITLE
Can eat a coin and a ghost at the same time.

### ISSUE THREAD

**Issue by DavidBetteridge** [YorkCodeDojo/PacMan#108]
If a square contains both an edible ghost and a coin,  then when PacMan moves onto that square both should be eaten.  I think currently only the Ghost is eaten.

**Comment by DavidBetteridge** [comment]
Also applies to squares containing pills and fruit in addition to ghosts

**Comment by SteveDunn** [comment]
Don't forget that you can have up to 4 ghosts in one cell. I did, and I've yet to fix it
