### ISSUE TITLE
PacMan shouldn't be able to stop by pushing against a wall

### ISSUE THREAD

**Issue by pgillett** [YorkCodeDojo/PacMan#30]
PacMan is always moving. He only stops if he runs into a wall. eg. while moving horizontally, you can not stop by pushing up against a wall

**Comment by DavidBetteridge** [comment]
This means that you can't ChangeDirection to face a wall.

**Comment by pgillett** [comment]
Yes, only allow ChangeDirection if the target space is not a wall. This will allow turning back on yourself.

**Comment by DavidBetteridge** [comment]
Steps are

- [ ] Add failing tests to PacManTests

- [ ] Add checks to ChangeDirection along the lines of

if (Direction = Direction.Up && !_settings.Walls.Contains((pacMan.X, pacMan.Y -1 )

etc....

**Comment by pgillett** [comment]
Or, using your new methods something like
if(!_settings.Wall.Contains(pacMan.Location.Move(Direction))
