### ISSUE TITLE
Increase the players score after eating a ghost

### ISSUE THREAD

**Issue by DavidBetteridge** [YorkCodeDojo/PacMan#56]
Eating a ghost in the same energizer period gives you 200 points, and double that for every additional ghost you eat (400, 800 and 1600 for the 2nd through 4th ghost, respectively).

I think this means we need keep track of the eaten ghosts on the game state.

**Comment by kevbite** [comment]
Not sure we have to keep track of them, we can just count them and use the following formula.

```csharp
var totalNotEdiable = ghosts.Count(x => !x.Ediable);
var scoreInc = 2^totalNotEdiable*200;
```

totalNotEdiable | scoreInc
-- | --
0 | 200
1 | 400
2 | 800
3 | 1600
4 | 3200
5 | 6400
6 | 12800
7 | 25600
8 | 51200
9 | 102400
10 | 204800

**Comment by DavidBetteridge** [comment]
Looks good

**Comment by DavidBetteridge** [comment]
- [ ] Write failing test in **GhostTests**

- [ ] Initially at least add a new method on **IGameActions** to return the number of edible ghosts.  (I expect this will-be refactored out later)

- [ ] Add code to the **GhostCollision** event in the **GameStateMachine**.

**Comment by kevbite** [comment]
Closed with https://github.com/YorkCodeDojo/PacMan/commit/e7dc101c106ce0a5cc3ef05e601ee27ea7fe6842
