### ISSUE TITLE
Implement bonus fruit

### ISSUE THREAD

**Issue by pgillett** [YorkCodeDojo/PacMan#83]
Cherry 100
Strawberry 300
Orange 500
Bell 700
Apple 1000
Grapes 2000
Arcadian 3000
Key 5000

Appears in the gap directly above PacMan starting position after 70 and 170 pills eaten and stays for about 10 seconds.

SpriteMap.Bonus[x] should give the correct sprite.

**Comment by kevbite** [comment]
🍒 
🍓
🍊
🔔
🍏
🍇
🔑

**Comment by kevbite** [comment]
Completed.
