### ISSUE TITLE
Game should get harder

### ISSUE THREAD

**Issue by DavidBetteridge** [YorkCodeDojo/PacMan#96]
The game should get harder when the player moves onto the next level.  For example the pill lasts for less time.

**Comment by pgillett** [comment]
Frightened times in seconds:

    private readonly int[] _frightenedTimes = new int[] {6, 5, 4, 3, 2, 5, 2, 2, 1, 5, 2, 1, 1, 3, 1, 1, 0, 1}; 
    public` int FrightenedTime => _level < _frightenedTimes.Length ? _frightenedTimes[_level] : 0;`

Number of frightened flashes (think these correspond to 28 frames in the arcade version):

    private int FrightenedFlashes => FrightenedTime < 2 ? 3 : 5;

These are all the speeds in percentage of full speed. As far as I can tell, 80% is a move every tick at 60FPS.

PacMan (chase/scatter):

    public int PacManSpeed
    {
         get
         {
             if (_level == 0) return 80;
             if (_level >= 4 && _level <= 19) return 90;
             return 100;
         }
     }

PacMan (frightened):

     public int PacManFrightenedSpeed
     {
         get
         {
             if (_level == 0) return 90;
             if (_level >= 4 && _level <= 19) return 100;
             return 95;
         }
     }

Ghost (normal speed):

     public int GhostSpeed
     {
         get
         {
             if (_level == 0) return 75;
             if (_level < 4 ) return 85;
             return 95;
         }
     }

"Cruise Elroy" speed:

     public int ElroySpeed(int pillsLeft)
     {
         var elroy = ElroyPoint;
         if (pillsLeft <= elroy / 2)
         {
             if (_level == 0) return 85;
             if (_level < 4) return 95;
             return 105;
         }

         if (pillsLeft < elroy)
         {
             if (_level == 0) return 80;
             if (_level < 4) return 90;
             return 100;
         }

         return GhostSpeed;
     }

The pills-left where Elroy kicks in:

     private int ElroyPoint
     {
         get
         {
             switch (_level)
             {
                 case 0:
                     return 20;
                 case 1:
                     return 30;
                 case 2:
                 case 3:
                 case 4:
                     return 40;
                 case 5:
                 case 6:
                 case 7:
                     return 50;
                 case 8:
                 case 9:
                 case 10:
                     return 60;
                 case 11:
                 case 12:
                 case 13:
                     return 80;
                 case 14:
                 case 15:
                 case 16:
                 case 17:
                     return 100;
                 default:
                     return 120;
             }
         }
     }

Ghost speed in frightened mode:

     public int GhostFrightenedSpeed
     {
         get
         {
             if (_level == 0) return 50;
             if (_level < 4) return 55;
             return 60;
         }
     }

For completeness, ghost travelling along tunnel speed:

     public int GhostTunnelSpeed
     {
         get
         {
             if (_level == 0) return 40;
             if (_level < 4) return 45;
             return 50;
         }
     }

**Comment by SteveDunn** [comment]
There are a LOT of variables that make the game harder as it goes along. There's even subtle ones  that make it harder that are not level related, e.g pac goes slower when 'eating'. Feel free to use the data from my repo which was collated from various technical documents https://github.com/SteveDunn/PacManBlazor/blob/master/src/PacMan.GameComponents/LevelStats.cs

**Comment by kevbite** [comment]
Thanks @SteveDunn, we'll take a look.
